/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/onboarding/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 온보딩 정보 저장
         * @description 이름·생년월일·주소·이메일·성별 등을 저장하고 온보딩을 완료 처리합니다. 모든 필드가 선택값이고 보내지 않은 필드는 기존 값을 유지하므로, 다시 호출하면 프로필 수정으로도 쓸 수 있습니다.
         */
        post: operations["saveOnboardingProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 검증 (개발 전용)
         * @description 토큰을 넣으면 서버가 그 토큰을 어떻게 판단하는지 알려줍니다. 만료 여부, access/refresh 중 무엇으로 유효한지, DB 저장값과 일치하는지를 확인할 수 있습니다.
         */
        post: operations["verifyToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 임시 토큰 발급 (개발 전용)
         * @description 소셜 로그인을 거치지 않고 토큰을 발급받습니다. providerId에 해당하는 회원이 없으면 그 자리에서 만듭니다. 모든 프로필에서 등록됩니다.
         */
        post: operations["issueToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 최근 대화한 채팅방 목록
         * @description 마지막 메시지 ID 내림차순으로 내려온다. 내가 나간 방과 메시지가 하나도 없는 방은 제외된다. 다음 페이지는 응답의 nextCursor를 cursor로 넘긴다.
         */
        get: operations["getChats"];
        put?: never;
        /**
         * 채팅방 생성
         * @description 상대와의 활성 채팅방을 확보합니다. 이미 있으면 새로 만들지 않고 그 방을 반환하며(created=false), 한쪽이라도 나간 방밖에 없으면 새 방을 만듭니다(created=true). 방을 만든 직후에는 메시지가 없어 채팅방 목록에는 아직 나타나지 않습니다.
         */
        post: operations["createRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{roomId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 채팅 내역 조회
         * @description cursor는 과거 방향(최신순), after는 미래 방향(오래된 순)이다. 둘 다 오면 after가 우선한다. after는 소켓이 끊긴 동안 온 메시지를 채우는 용도다.
         */
        get: operations["getMessages"];
        put?: never;
        /**
         * 메시지 보내기
         * @description TEXT 메시지만 받는다. 상대가 나간 방에는 보낼 수 없다(CHAT4033). 보내는 순간 내 읽음 포인터도 함께 옮겨가므로, 방금 보낸 메시지가 내 unreadCount에 잡히지 않는다.
         */
        post: operations["sendMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reissue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 재발급
         * @description refresh 토큰으로 access와 refresh를 모두 새로 발급합니다. 기존 refresh는 폐기됩니다. 인증이 필요 없습니다.
         */
        post: operations["reissue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 저장된 refresh 토큰을 삭제합니다. 이미 삭제되어 있어도 성공으로 처리합니다.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 소셜 회원가입/로그인
         * @description 소셜 계정이 없으면 가입 후 로그인, 있으면 바로 로그인합니다. 인증이 필요 없습니다.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createFeed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feed/heart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyFeedHeartHistory"];
        put?: never;
        post: operations["toggleHeart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/call": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startCall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/call/{callId}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["endCall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{roomId}/read-receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 메시지 읽음 처리
         * @description lastReadMessageId 이하의 상대 메시지를 모두 읽음으로 표시한다. 이 방의 메시지가 아니면 CHAT4042. 저장된 값보다 작은 ID는 무시되며, 응답에는 요청값이 아니라 실제로 저장된 포인터가 내려간다.
         */
        patch: operations["readMessages"];
        trace?: never;
    };
    "/api/v1/feed/{feedId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFeed"];
        put?: never;
        post?: never;
        delete: operations["deleteFeed"];
        options?: never;
        head?: never;
        patch: operations["updateFeed"];
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 정보 조회
         * @description access 토큰의 회원 정보를 반환합니다. 온보딩 전에도 호출할 수 있으며, 이 경우 이름·전화번호·주소·성별·생년월일·자기소개서가 전부 null입니다.
         */
        get: operations["getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats/{roomId}/member/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 채팅방 나가기
         * @description 본인만 방에서 나가며 방은 삭제되지 않는다. 다시 들어올 수 없고, 상대는 이 방에 더 이상 메시지를 보낼 수 없다(CHAT4033). 이미 나간 방이면 CHAT4032. 같은 상대와 다시 대화하려면 채팅방 생성 API로 새 방을 만든다.
         */
        delete: operations["leaveRoom"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/withdrawal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 회원탈퇴
         * @description 회원을 탈퇴 처리하고 저장된 refresh 토큰을 삭제합니다. 채팅 메시지는 보존되며, 같은 소셜 계정으로 다시 로그인하면 신규 회원으로 가입됩니다.
         */
        delete: operations["withdraw"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OnboardingProfileDTO: {
            /**
             * @description 이름
             * @example 김티움
             */
            name?: string;
            /**
             * Format: date
             * @description 생년월일 (yyyy-MM-dd)
             * @example 1998-05-12
             */
            birthDate?: string;
            /**
             * @description 기본주소와 상세주소를 합친 한 문자열
             * @example 경기도 부천시 원미구 ... 101동 1001호
             */
            address?: string;
            /**
             * Format: email
             * @description 소셜 로그인 시 받아둔 값이 있으면 여기서 수정할 수 있다.
             * @example user@example.com
             */
            email?: string;
            /**
             * @description 성별
             * @example MALE
             * @enum {string}
             */
            gender?: "MALE" | "FEMALE";
            /**
             * @description 본인인증 없이 값만 저장한다.
             * @example 010-1234-5678
             */
            phoneNumber?: string;
            /** @description 자기소개서 본문. 온보딩 화면에는 입력란이 없고 프로필 수정에서 전달한다. */
            introduction?: string;
        };
        ApiResponseMyProfileDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["MyProfileDTO"];
        };
        MyProfileDTO: {
            /** Format: int64 */
            memberId?: number;
            name?: string;
            email?: string;
            phoneNumber?: string;
            address?: string;
            /** @enum {string} */
            gender?: "MALE" | "FEMALE";
            /** Format: date */
            birthDate?: string;
            introduction?: string;
            onboardingCompleted?: boolean;
        };
        DevVerifyDTO: {
            /** @description 검증할 access 또는 refresh 토큰 */
            token: string;
        };
        ApiResponseDevVerifyResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["DevVerifyResultDTO"];
        };
        DevVerifyResultDTO: {
            expired?: boolean;
            validAsAccessToken?: boolean;
            validAsRefreshToken?: boolean;
            /** Format: int64 */
            memberId?: number;
            matchesStoredRefreshToken?: boolean;
            verdict?: string;
        };
        DevTokenDTO: {
            /**
             * @description 테스트 회원 식별자. 없으면 그 자리에서 회원을 만든다.
             * @example test-user-1
             */
            providerId: string;
        };
        ApiResponseDevTokenResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["DevTokenResultDTO"];
        };
        DevTokenResultDTO: {
            /** Format: int64 */
            memberId?: number;
            accessToken?: string;
            refreshToken?: string;
            isNewMember?: boolean;
            onboardingCompleted?: boolean;
        };
        CreateRoomDTO: {
            /**
             * Format: int64
             * @description 대화할 상대 회원 ID
             * @example 15
             */
            opponentId: number;
        };
        ApiResponseCreateRoomResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["CreateRoomResultDTO"];
        };
        CreateRoomResultDTO: {
            /**
             * Format: int64
             * @description 채팅방 ID
             * @example 101
             */
            roomId?: number;
            /**
             * @description true면 새로 만든 방, false면 기존 활성 방을 그대로 반환
             * @example true
             */
            created?: boolean;
            opponent?: components["schemas"]["OpponentDTO"];
        };
        OpponentDTO: {
            /**
             * Format: int64
             * @description 상대방 회원 ID
             * @example 15
             */
            userId?: number;
            /**
             * @description 상대방 닉네임. member.name을 쓴다
             * @example 김티움
             */
            nickname?: string;
            /** @description 상대방 프로필 이미지 URL. 업로드 경로 미정이라 현재는 항상 null */
            profileImageUrl?: string;
        };
        SendMessageDTO: {
            /**
             * @description 메시지 타입. 현재는 TEXT만 허용한다
             * @example TEXT
             * @enum {string}
             */
            type?: "TEXT" | "IMAGE" | "SYSTEM";
            /**
             * @description 메시지 내용
             * @example 저도 오늘 즐거웠어요!
             */
            content?: string;
        };
        ApiResponseSendMessageResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["SendMessageResultDTO"];
        };
        SendMessageResultDTO: {
            /**
             * Format: int64
             * @description 생성된 메시지 ID
             * @example 986
             */
            messageId?: number;
            /**
             * Format: int64
             * @description 채팅방 ID
             * @example 101
             */
            roomId?: number;
            /**
             * Format: int64
             * @description 보낸 사람 ID
             * @example 8
             */
            senderId?: number;
            /** @enum {string} */
            type?: "TEXT" | "IMAGE" | "SYSTEM";
            content?: string;
            /** Format: date-time */
            sentAt?: string;
        };
        ReissueDTO: {
            refreshToken?: string;
        };
        ApiResponseReissueResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["ReissueResultDTO"];
        };
        ReissueResultDTO: {
            accessToken?: string;
            refreshToken?: string;
        };
        ApiResponseVoid: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: unknown;
        };
        LoginDTO: {
            token?: string;
            authorizationCode?: string;
        };
        ApiResponseLoginResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["LoginResultDTO"];
        };
        LoginResultDTO: {
            /** Format: int64 */
            memberId?: number;
            accessToken?: string;
            refreshToken?: string;
            isNewMember?: boolean;
            onboardingCompleted?: boolean;
        };
        FeedDTO: {
            content: string;
        };
        ApiResponseFeedResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["FeedResultDTO"];
        };
        FeedResultDTO: {
            /** Format: int64 */
            feedId?: number;
            content?: string;
            /** Format: int64 */
            heart?: number;
        };
        FeedHeartDTO: {
            /** Format: int64 */
            feedId: number;
        };
        ApiResponseFeedHeartResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["FeedHeartResultDTO"];
        };
        FeedHeartResultDTO: {
            /** Format: int64 */
            feedId?: number;
            /** Format: int64 */
            heart?: number;
            heartYn?: string;
        };
        CallStartDTO: {
            /** @enum {string} */
            type: "VOICE" | "VIDEO";
            participantIds?: number[];
        };
        ApiResponseCallResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["CallResultDTO"];
        };
        CallResultDTO: {
            /** Format: int64 */
            callId?: number;
            /** @enum {string} */
            type?: "VOICE" | "VIDEO";
            /** @enum {string} */
            status?: "IN_PROGRESS" | "COMPLETED";
            /** Format: date-time */
            startAt?: string;
            /** Format: date-time */
            endAt?: string;
            participantIds?: number[];
        };
        ReadMessageDTO: {
            /**
             * Format: int64
             * @description 여기까지 읽었다고 표시할 마지막 메시지 ID
             * @example 986
             */
            lastReadMessageId: number;
        };
        ApiResponseReadMessageResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["ReadMessageResultDTO"];
        };
        ReadMessageResultDTO: {
            /**
             * Format: int64
             * @description 채팅방 ID
             * @example 101
             */
            roomId?: number;
            /**
             * Format: int64
             * @description 처리된 마지막 읽음 메시지 ID
             * @example 986
             */
            lastReadMessageId?: number;
            /**
             * Format: date-time
             * @description 읽음 처리 시각
             */
            readAt?: string;
        };
        ApiResponseGetChatDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["GetChatDTO"];
        };
        ChatRoomDTO: {
            /** Format: int64 */
            roomId?: number;
            opponentLeft?: boolean;
            opponent?: components["schemas"]["OpponentDTO"];
            lastMessage?: components["schemas"]["LastMessageDTO"];
            /** Format: int64 */
            unreadCount?: number;
        };
        GetChatDTO: {
            rooms?: components["schemas"]["ChatRoomDTO"][];
            hasNext?: boolean;
            /** Format: int64 */
            nextCursor?: number;
        };
        LastMessageDTO: {
            /** Format: int64 */
            messageId?: number;
            content?: string;
            /** @enum {string} */
            type?: "TEXT" | "IMAGE" | "SYSTEM";
            /** Format: date-time */
            sentAt?: string;
        };
        ApiResponseGetMessagesDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["GetMessagesDTO"];
        };
        GetMessagesDTO: {
            /** Format: int64 */
            roomId?: number;
            opponent?: components["schemas"]["OpponentDTO"];
            opponentLeft?: boolean;
            messages?: components["schemas"]["MessageDTO"][];
            hasNext?: boolean;
            /** Format: int64 */
            nextCursor?: number;
        };
        MessageDTO: {
            /**
             * Format: int64
             * @description 메시지 ID
             * @example 985
             */
            messageId?: number;
            /**
             * Format: int64
             * @description 보낸 사람 ID. SYSTEM 타입은 null
             * @example 15
             */
            senderId?: number;
            /** @enum {string} */
            type?: "TEXT" | "IMAGE" | "SYSTEM";
            /** @description 메시지 내용. IMAGE면 이미지 URL */
            content?: string;
            /** Format: date-time */
            sentAt?: string;
            /**
             * @description 상대가 읽었는지. 내가 보낸 메시지에만 의미가 있다
             * @example true
             */
            isRead?: boolean;
        };
        ApiResponseListFeedHeartHistoryDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["FeedHeartHistoryDTO"][];
        };
        FeedHeartHistoryDTO: {
            /** Format: int64 */
            feedId?: number;
            /** Format: int64 */
            memberId?: number;
            /** Format: date-time */
            heartedAt?: string;
        };
        ApiResponseLeaveRoomResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["LeaveRoomResultDTO"];
        };
        LeaveRoomResultDTO: {
            /**
             * Format: int64
             * @description 채팅방 ID
             * @example 101
             */
            roomId?: number;
            /**
             * Format: date-time
             * @description 나간 시각
             */
            leftAt?: string;
        };
        ApiResponseWithdrawalResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["WithdrawalResultDTO"];
        };
        WithdrawalResultDTO: {
            /** Format: int64 */
            memberId?: number;
            /** Format: date-time */
            withdrawnAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    saveOnboardingProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingProfileDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMyProfileDTO"];
                };
            };
        };
    };
    verifyToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevVerifyDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDevVerifyResultDTO"];
                };
            };
        };
    };
    issueToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevTokenDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDevTokenResultDTO"];
                };
            };
        };
    };
    getChats: {
        parameters: {
            query?: {
                cursor?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGetChatDTO"];
                };
            };
        };
    };
    createRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoomDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCreateRoomResultDTO"];
                };
            };
        };
    };
    getMessages: {
        parameters: {
            query?: {
                cursor?: number;
                after?: number;
                size?: number;
            };
            header?: never;
            path: {
                roomId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGetMessagesDTO"];
                };
            };
        };
    };
    sendMessage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseSendMessageResultDTO"];
                };
            };
        };
    };
    reissue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReissueDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReissueResultDTO"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLoginResultDTO"];
                };
            };
        };
    };
    createFeed: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseFeedResultDTO"];
                };
            };
        };
    };
    getMyFeedHeartHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListFeedHeartHistoryDTO"];
                };
            };
        };
    };
    toggleHeart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedHeartDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseFeedHeartResultDTO"];
                };
            };
        };
    };
    startCall: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CallStartDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCallResultDTO"];
                };
            };
        };
    };
    endCall: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                callId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCallResultDTO"];
                };
            };
        };
    };
    readMessages: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReadMessageDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReadMessageResultDTO"];
                };
            };
        };
    };
    getFeed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseFeedResultDTO"];
                };
            };
        };
    };
    deleteFeed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    updateFeed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseFeedResultDTO"];
                };
            };
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMyProfileDTO"];
                };
            };
        };
    };
    leaveRoom: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLeaveRoomResultDTO"];
                };
            };
        };
    };
    withdraw: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWithdrawalResultDTO"];
                };
            };
        };
    };
}
