/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/onboarding/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 온보딩 정보 저장
         * @description 이름·생년월일·주소·이메일·성별 등을 저장하고 온보딩을 완료 처리합니다. 모든 필드가 선택값이고 보내지 않은 필드는 기존 값을 유지하므로, 다시 호출하면 프로필 수정으로도 쓸 수 있습니다.
         */
        post: operations["saveOnboardingProfile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 검증 (개발 전용)
         * @description 토큰을 넣으면 서버가 그 토큰을 어떻게 판단하는지 알려줍니다. 만료 여부, access/refresh 중 무엇으로 유효한지, DB 저장값과 일치하는지를 확인할 수 있습니다.
         */
        post: operations["verifyToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dev/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 임시 토큰 발급 (개발 전용)
         * @description 소셜 로그인을 거치지 않고 토큰을 발급받습니다. providerId에 해당하는 회원이 없으면 그 자리에서 만듭니다. 모든 프로필에서 등록됩니다.
         */
        post: operations["issueToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 채팅방 생성
         * @description 상대와의 활성 채팅방을 확보합니다. 이미 있으면 새로 만들지 않고 그 방을 반환하며(created=false), 한쪽이라도 나간 방밖에 없으면 새 방을 만듭니다(created=true). 방을 만든 직후에는 메시지가 없어 채팅방 목록에는 아직 나타나지 않습니다.
         */
        post: operations["createRoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reissue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 재발급
         * @description refresh 토큰으로 access와 refresh를 모두 새로 발급합니다. 기존 refresh는 폐기됩니다. 인증이 필요 없습니다.
         */
        post: operations["reissue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description 저장된 refresh 토큰을 삭제합니다. 이미 삭제되어 있어도 성공으로 처리합니다.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 소셜 회원가입/로그인
         * @description 소셜 계정이 없으면 가입 후 로그인, 있으면 바로 로그인합니다. 인증이 필요 없습니다.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createFeed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feed/heart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyFeedHeartHistory"];
        put?: never;
        post: operations["toggleHeart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feed/{feedId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getFeed"];
        put?: never;
        post?: never;
        delete: operations["deleteFeed"];
        options?: never;
        head?: never;
        patch: operations["updateFeed"];
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 정보 조회
         * @description access 토큰의 회원 정보를 반환합니다. 온보딩 전에도 호출할 수 있으며, 이 경우 이름·전화번호·주소·성별·생년월일·자기소개서가 전부 null입니다.
         */
        get: operations["getMyProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/withdrawal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 회원탈퇴
         * @description 회원을 탈퇴 처리하고 저장된 refresh 토큰을 삭제합니다. 채팅 메시지는 보존되며, 같은 소셜 계정으로 다시 로그인하면 신규 회원으로 가입됩니다.
         */
        delete: operations["withdraw"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        OnboardingProfileDTO: {
            /**
             * @description 이름
             * @example 김티움
             */
            name?: string;
            /**
             * Format: date
             * @description 생년월일 (yyyy-MM-dd)
             * @example 1998-05-12
             */
            birthDate?: string;
            /**
             * @description 기본주소와 상세주소를 합친 한 문자열
             * @example 경기도 부천시 원미구 ... 101동 1001호
             */
            address?: string;
            /**
             * Format: email
             * @description 소셜 로그인 시 받아둔 값이 있으면 여기서 수정할 수 있다.
             * @example user@example.com
             */
            email?: string;
            /**
             * @description 성별
             * @example MALE
             * @enum {string}
             */
            gender?: "MALE" | "FEMALE";
            /**
             * @description 본인인증 없이 값만 저장한다.
             * @example 010-1234-5678
             */
            phoneNumber?: string;
            /** @description 자기소개서 본문. 온보딩 화면에는 입력란이 없고 프로필 수정에서 전달한다. */
            introduction?: string;
        };
        ApiResponseMyProfileDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["MyProfileDTO"];
        };
        MyProfileDTO: {
            /** Format: int64 */
            memberId?: number;
            name?: string;
            email?: string;
            phoneNumber?: string;
            address?: string;
            /** @enum {string} */
            gender?: "MALE" | "FEMALE";
            /** Format: date */
            birthDate?: string;
            introduction?: string;
            onboardingCompleted?: boolean;
        };
        DevVerifyDTO: {
            /** @description 검증할 access 또는 refresh 토큰 */
            token: string;
        };
        ApiResponseDevVerifyResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["DevVerifyResultDTO"];
        };
        DevVerifyResultDTO: {
            expired?: boolean;
            validAsAccessToken?: boolean;
            validAsRefreshToken?: boolean;
            /** Format: int64 */
            memberId?: number;
            matchesStoredRefreshToken?: boolean;
            verdict?: string;
        };
        DevTokenDTO: {
            /**
             * @description 테스트 회원 식별자. 없으면 그 자리에서 회원을 만든다.
             * @example test-user-1
             */
            providerId: string;
        };
        ApiResponseDevTokenResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["DevTokenResultDTO"];
        };
        DevTokenResultDTO: {
            /** Format: int64 */
            memberId?: number;
            accessToken?: string;
            refreshToken?: string;
            isNewMember?: boolean;
            onboardingCompleted?: boolean;
        };
        CreateRoomDTO: {
            /**
             * Format: int64
             * @description 대화할 상대 회원 ID
             * @example 15
             */
            opponentId: number;
        };
        ApiResponseCreateRoomResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["CreateRoomResultDTO"];
        };
        CreateRoomResultDTO: {
            /**
             * Format: int64
             * @description 채팅방 ID
             * @example 101
             */
            roomId?: number;
            /**
             * @description true면 새로 만든 방, false면 기존 활성 방을 그대로 반환
             * @example true
             */
            created?: boolean;
            opponent?: components["schemas"]["OpponentDTO"];
        };
        OpponentDTO: {
            /**
             * Format: int64
             * @description 상대방 회원 ID
             * @example 15
             */
            userId?: number;
            /**
             * @description 상대방 닉네임. member.name을 쓴다
             * @example 김티움
             */
            nickname?: string;
            /** @description 상대방 프로필 이미지 URL. 업로드 경로 미정이라 현재는 항상 null */
            profileImageUrl?: string;
        };
        ReissueDTO: {
            refreshToken?: string;
        };
        ApiResponseReissueResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["ReissueResultDTO"];
        };
        ReissueResultDTO: {
            accessToken?: string;
            refreshToken?: string;
        };
        ApiResponseVoid: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: unknown;
        };
        LoginDTO: {
            token?: string;
            authorizationCode?: string;
        };
        ApiResponseLoginResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["LoginResultDTO"];
        };
        LoginResultDTO: {
            /** Format: int64 */
            memberId?: number;
            accessToken?: string;
            refreshToken?: string;
            isNewMember?: boolean;
            onboardingCompleted?: boolean;
        };
        FeedDTO: {
            content: string;
        };
        ApiResponseFeedResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["FeedResultDTO"];
        };
        FeedResultDTO: {
            /** Format: int64 */
            feedId?: number;
            content?: string;
            /** Format: int64 */
            heart?: number;
        };
        FeedHeartDTO: {
            /** Format: int64 */
            feedId: number;
        };
        ApiResponseFeedHeartResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["FeedHeartResultDTO"];
        };
        FeedHeartResultDTO: {
            /** Format: int64 */
            feedId?: number;
            /** Format: int64 */
            heart?: number;
            heartYn?: string;
        };
        ApiResponseListFeedHeartHistoryDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["FeedHeartHistoryDTO"][];
        };
        FeedHeartHistoryDTO: {
            /** Format: int64 */
            feedId?: number;
            /** Format: int64 */
            memberId?: number;
            /** Format: date-time */
            heartedAt?: string;
        };
        ApiResponseWithdrawalResultDTO: {
            isSuccess?: boolean;
            code?: string;
            message?: string;
            result?: components["schemas"]["WithdrawalResultDTO"];
        };
        WithdrawalResultDTO: {
            /** Format: int64 */
            memberId?: number;
            /** Format: date-time */
            withdrawnAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    saveOnboardingProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingProfileDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMyProfileDTO"];
                };
            };
        };
    };
    verifyToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevVerifyDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDevVerifyResultDTO"];
                };
            };
        };
    };
    issueToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevTokenDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDevTokenResultDTO"];
                };
            };
        };
    };
    createRoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoomDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCreateRoomResultDTO"];
                };
            };
        };
    };
    reissue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReissueDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseReissueResultDTO"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLoginResultDTO"];
                };
            };
        };
    };
    createFeed: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseFeedResultDTO"];
                };
            };
        };
    };
    getMyFeedHeartHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListFeedHeartHistoryDTO"];
                };
            };
        };
    };
    toggleHeart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedHeartDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseFeedHeartResultDTO"];
                };
            };
        };
    };
    getFeed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseFeedResultDTO"];
                };
            };
        };
    };
    deleteFeed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    updateFeed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                feedId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseFeedResultDTO"];
                };
            };
        };
    };
    getMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMyProfileDTO"];
                };
            };
        };
    };
    withdraw: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWithdrawalResultDTO"];
                };
            };
        };
    };
}
